apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-auth-deployment
spec:
  selector:
    matchLabels:
      app: backend-auth-app
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-auth-app
    spec:
      containers:
        - name: backend-auth-app
          image: us-central1-docker.pkg.dev/ultimate-bit-416621/my-artifact-registry/naveen-auth-image:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-auth-service
spec:
  selector:
    app: backend-auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
