apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-ingress
spec:
  rules:
    - host: mystore.com
      http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: frontend-service
          #       port:
          #         number: 80
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-auth-service
                port:
                  number: 80
