apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpack-ts-deployment
spec:
  selector:
    matchLabels:
      app: webpack-ts-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: webpack-ts-pod
    spec:
      containers:
        - name: webpack-ts-container
          image: webpack-ts-image-test:0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080