apiVersion: v1
kind: Service
metadata:
  name: webpack-ts-service
spec:
  selector:
    app: webpack-ts-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
      nodePort: 31001
  type: NodePort