apiVersion: v1
kind: Namespace
metadata:
  name: shopping-cart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment-nginx
  namespace: shopping-cart
spec:
  selector:
    matchLabels:
      app: shopping-cart-app
  template:
    metadata:
      labels:
        app: shopping-cart-app
    spec:
      containers:
        - name: shopping-cart-container-nginx
          image: webpack-ts-image-test:0.4
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service-nginx
  namespace: shopping-cart
spec:
  selector:
    app: shopping-cart-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-cart-ingress-nginx
  namespace: shopping-cart
spec:
  ingressClassName: nginx
  rules:
    - host: webpack-ingress.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopping-cart-service-nginx
                port:
                  number: 5000
