apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyle-react-deployment
spec:
  selector:
    matchLabels:
      app: kyle-react
  replicas: 1
  template:
    metadata:
      labels:
        app: kyle-react
    spec:
      containers:
        - name: kyle-react
          image: us-central1-docker.pkg.dev/ultimate-bit-416621/my-artifact-registry/sample-image:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kyle-react-service
spec:
  selector:
    app: kyle-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
