apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-auth-deployment
spec:
  selector:
    matchLabels:
      app: backend-auth-app
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-auth-app
    spec:
      containers:
        - name: backend-auth-app
          image: ap-hyderabad-1.ocir.io/axu4lyhxbeg6/backend-image-oracle:0.1
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: babu-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-auth-service
spec:
  selector:
    app: backend-auth-app
  ports:
    - port: 80
      targetPort: 4000
