apiVersion: v1
kind: Service
metadata:
  name: webpack-ts-service-v1
  namespace: sample
spec:
  selector:
    app: webpack-ts-pod-v1
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort